CREATE TABLE IF NOT EXISTS request_attempt_log (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    trace_id VARCHAR(64) NOT NULL,
    protocol_type VARCHAR(32) NOT NULL,
    client_id BIGINT NULL,
    virtual_model_id BIGINT NULL,
    virtual_model_code VARCHAR(128) NULL,
    requested_model VARCHAR(128) NULL,
    binding_id BIGINT NULL,
    provider_id BIGINT NULL,
    provider_key_id BIGINT NULL,
    upstream_model_name VARCHAR(128) NULL,
    attempt_level VARCHAR(32) NOT NULL,
    attempt_order INT NOT NULL DEFAULT 1,
    trigger_reason VARCHAR(64) NOT NULL,
    request_summary_json JSON NULL,
    response_summary_json JSON NULL,
    status_code INT NULL,
    success TINYINT(1) NOT NULL DEFAULT 0,
    latency_ms INT NULL,
    error_code VARCHAR(64) NULL,
    error_message VARCHAR(255) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    KEY idx_request_attempt_log_trace_id (trace_id, created_at),
    KEY idx_request_attempt_log_binding_created_at (binding_id, created_at),
    KEY idx_request_attempt_log_provider_created_at (provider_id, created_at),
    KEY idx_request_attempt_log_provider_key_created_at (provider_key_id, created_at),
    KEY idx_request_attempt_log_success_created_at (success, created_at),
    CONSTRAINT fk_request_attempt_log_client FOREIGN KEY (client_id) REFERENCES api_client(id) ON DELETE SET NULL,
    CONSTRAINT fk_request_attempt_log_virtual_model FOREIGN KEY (virtual_model_id) REFERENCES virtual_model(id) ON DELETE SET NULL,
    CONSTRAINT fk_request_attempt_log_binding FOREIGN KEY (binding_id) REFERENCES virtual_model_binding(id) ON DELETE SET NULL,
    CONSTRAINT fk_request_attempt_log_provider FOREIGN KEY (provider_id) REFERENCES provider(id) ON DELETE SET NULL,
    CONSTRAINT fk_request_attempt_log_provider_key FOREIGN KEY (provider_key_id) REFERENCES provider_key(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
